import { ConsensusResult } from '../consensus/index.js';
import { summarizeFindings } from '../consensus/ranker.js';
import { Severity } from '../consensus/types.js';

function getSeverityEmoji(severity: Severity): string {
  switch (severity) {
    case 'critical':
      return '🔴';
    case 'high':
      return '🟠';
    case 'medium':
      return '🟡';
    case 'low':
      return '🔵';
    case 'info':
      return 'ℹ️';
  }
}

export function formatMarkdownOutput(result: ConsensusResult): string {
  const lines: string[] = [];

  // Header
  lines.push('# 🏛️ Review Council Report\n');

  // Summary
  const summary = summarizeFindings(result.findings);
  lines.push('## Summary\n');
  lines.push(`- **Total Findings**: ${summary.total}`);
  lines.push(`- **Unanimous**: ${summary.unanimous}`);
  lines.push(`- **Elevated**: ${summary.elevated}`);
  lines.push(`- **Models**: ${result.successCount} successful, ${result.failureCount} failed\n`);

  // Severity breakdown
  lines.push('### By Severity\n');
  for (const [severity, count] of Object.entries(summary.bySeverity)) {
    if (count > 0) {
      const emoji = getSeverityEmoji(severity as Severity);
      lines.push(`- ${emoji} **${severity}**: ${count}`);
    }
  }
  lines.push('');

  // Consensus breakdown
  lines.push('### By Consensus\n');
  for (const { modelCount, count } of summary.byModels) {
    const percentage = Math.round((modelCount / result.successCount) * 100);
    lines.push(`- **${modelCount}/${result.successCount}** models (${percentage}%): ${count} finding${count !== 1 ? 's' : ''}`);
  }
  lines.push('');

  // Model results
  lines.push('## Model Results\n');
  for (const review of result.reviews) {
    const status = review.success ? '✅' : '❌';
    lines.push(`### ${status} ${review.provider}/${review.model}\n`);
    lines.push(`- **Status**: ${review.success ? 'Success' : 'Failed'}`);
    lines.push(`- **Duration**: ${review.durationMs}ms`);
    if (review.success) {
      lines.push(`- **Findings**: ${review.findings.length}`);
    }
    if (!review.success && review.error) {
      lines.push(`- **Error**: ${review.error}`);
    }
    lines.push('');
  }

  // Findings
  if (result.findings.length === 0) {
    lines.push('## ✨ No Issues Found!\n');
    return lines.join('\n');
  }

  lines.push('## Findings\n');

  for (let i = 0; i < result.findings.length; i++) {
    const finding = result.findings[i];
    const emoji = getSeverityEmoji(finding.severity);

    lines.push(`### ${i + 1}. ${emoji} ${finding.severity.toUpperCase()} - ${finding.category}\n`);
    lines.push(`**Location**: \`${finding.file}:${finding.line}\`\n`);
    lines.push(`**Message**: ${finding.message}\n`);

    // Consensus info
    const consensus = Math.round(finding.consensusScore * 100);
    let consensusText = `**Consensus**: ${consensus}% (${finding.modelCount}/${finding.totalModels} models)`;

    if (finding.unanimous) {
      consensusText += ' ✅ **UNANIMOUS**';
    }
    if (finding.elevated) {
      consensusText += ` ⬆️ Elevated from \`${finding.originalSeverity}\``;
    }

    lines.push(consensusText + '\n');
    lines.push(`**Models**: ${finding.models.join(', ')}\n`);

    if (finding.suggestion) {
      lines.push(`**Suggestion**: ${finding.suggestion}\n`);
    }

    lines.push('---\n');
  }

  lines.push('*Generated by Review Council*');

  return lines.join('\n');
}
